# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter Mate
        # You may pin to the exact commit or the version.
        # uses: techno-disaster/Flutter-Mate@5a1eb05c542ab8dbda92eec7290f5b79c6371f4e
        uses: techno-disaster/Flutter-Mate@v1.0.0

